#!/usr/bin/env python3
"""dot.modular knob assets — fluted, meloDICER-family.

WHAT WAS WRONG. The old knobs modelled the flutes as 18 ELLIPSES painted on the FACE
(rx=1.44 ry=2.88 at r=8.1, gradient-filled). A real fluted knob has no marks on its face:
the flutes are notches cut into the SILHOUETTE. Painted ovals on a flat disc read as
bubbles or dimples, which is exactly how they looked.

WHAT THIS DOES. The body is a single scalloped path -- r(theta) = R - a*(1+cos(N*theta))/2
-- so the flutes are the outline. The cap is a plain disc, the pointer a plain line.

NO GRADIENTS, NO FILTERS. The old assets used radialGradient (18 url() refs in the cream
large) and an feDropShadow filter. nanosvg has no filter support at all, so that shadow has
never rendered; and Rack's svgDraw collapses a gradient to its FIRST and LAST stop, so a
3-stop gradient silently loses its middle. Depth here is solid concentric fills instead:
same result, no dependence on either tolerance. (Rack's SvgKnob also adds its own
CircularShadow, which we disable in MonsoonWidget -- see the note there.)

FOOTPRINTS ARE PRESERVED EXACTLY. SvgKnob sizes its box from the SVG, so changing viewBox
or width would move every knob on every panel. Each generated file keeps the viewBox and
px size of the file it replaces; only the artwork inside changes.
"""
import math

# name -> (viewBox half-extent mm, px width, body radius mm, palette)
# Footprints copied from the existing assets. Small/Straits sizes are new but reuse the
# same 2.9527559 px/mm scale so they sit on the same grid.
CREAM = dict(body='#e9e3d2', bodyLo='#d8d1bd', cap='#f4f0e4', capRim='#c9c2ad',
             edge='#2b2620', flute='#b9b2a0', pointer='#1b1815')
DARK  = dict(body='#2e2e2e', bodyLo='#1f1f1f', cap='#3a3a3a', capRim='#141414',
             edge='#0b0b0b', flute='#141414', pointer='#e8e8e8')

SPECS = [
    # existing — footprints must not change
    ('RDM_KnobCream_Large',  13.500, 79.724, 9.00, CREAM),
    ('RDM_KnobCream_Medium', 11.000, 64.961, 6.50, CREAM),
    ('RDM_KnobDark_Large',   13.500, 79.724, 9.00, DARK),
    ('RDM_KnobDark_Medium',  11.000, 64.961, 6.50, DARK),
    ('RDM_KnobLarge',        10.500, 62.010, 8.30, DARK),
    ('RDM_KnobMedium',        9.000, 53.150, 6.60, DARK),
    ('RDM_KnobSmall',         8.000, 47.240, 5.60, DARK),
    # new — small cream/dark, and a Trimpot-scale pair for the Straits expanders so the
    # brand reads at expander scale too. NOTE these do not need to match Rack's Trimpot
    # footprint: SvgKnob sizes its box from OUR svg and the kit anchors by CENTRE, so a
    # swap of bindParam<Trimpot> -> bindParam<RDM_TrimDark> just renders our art at our
    # size. The 8mm body is a starting point, tune TRIM_R if it crowds the Straits rows.
    ('RDM_KnobCream_Small',   8.000, 47.240, 5.60, CREAM),
    ('RDM_KnobDark_Small',    8.000, 47.240, 5.60, DARK),
    ('RDM_TrimCream',         5.500, 32.480, 4.00, CREAM),
    ('RDM_TrimDark',          5.500, 32.480, 4.00, DARK),
]

FLUTES     = 20      # meloDICER reads ~18-20 around the skirt
FLUTE_DEEP = 0.075   # scallop depth as a fraction of R
CAP_FRAC   = 0.66    # smooth cap radius / R -- the flutes live in the skirt outside it
PTR_IN     = 0.10    # pointer, fraction of R
PTR_OUT    = 0.58

def scallop_path(R, n=FLUTES, depth=FLUTE_DEEP, steps=16):
    """Fluted silhouette: flutes are the OUTLINE, not paint on the face."""
    pts = []
    for k in range(n * steps):
        th = 2.0 * math.pi * k / (n * steps)
        r  = R - R * depth * (1.0 + math.cos(n * th)) * 0.5
        pts.append((r * math.cos(th), r * math.sin(th)))
    d = 'M %.3f %.3f ' % pts[0] + ' '.join('L %.3f %.3f' % p for p in pts[1:]) + ' Z'
    return d

def build(half, px, R, c):
    # Flute count scales with size: 20 crests on a 4mm-radius trim knob would alias into a
    # blur at any sane zoom, so drop to 12 below ~5mm.
    global FLUTES
    FLUTES = 20 if R >= 5.0 else 12
    L = ['<?xml version="1.0" encoding="UTF-8"?>',
         '<svg xmlns="http://www.w3.org/2000/svg" width="%.3f" height="%.3f" '
         'viewBox="%.3f %.3f %.3f %.3f">' % (px, px, -half, -half, 2*half, 2*half),
         '<!-- generated by panel_src/gen_knobs.py : do not hand-edit -->']
    # skirt: fluted silhouette
    L.append('<path d="%s" fill="%s" stroke="%s" stroke-width="0.30" stroke-linejoin="round"/>'
             % (scallop_path(R), c['body'], c['edge']))
    # one short dark stroke per flute valley, so the flutes read even head-on
    for i in range(FLUTES):
        th = 2.0 * math.pi * (i + 0.5) / FLUTES          # valley sits between crests
        r0, r1 = R * (CAP_FRAC + 0.04), R * (1.0 - FLUTE_DEEP)
        L.append('<line x1="%.3f" y1="%.3f" x2="%.3f" y2="%.3f" stroke="%s" '
                 'stroke-width="0.22" opacity="0.55" stroke-linecap="round"/>'
                 % (r0*math.cos(th), r0*math.sin(th), r1*math.cos(th), r1*math.sin(th), c['flute']))
    # depth: solid concentric fills, no gradient (see the header)
    L.append('<circle cx="0" cy="0" r="%.3f" fill="%s"/>' % (R * (CAP_FRAC + 0.05), c['bodyLo']))
    L.append('<circle cx="0" cy="0" r="%.3f" fill="%s" stroke="%s" stroke-width="0.22"/>'
             % (R * CAP_FRAC, c['cap'], c['capRim']))
    # pointer: straight up at 0 rotation, as Rack expects
    L.append('<line x1="0" y1="%.3f" x2="0" y2="%.3f" stroke="%s" stroke-width="%.3f" '
             'stroke-linecap="round"/>' % (-R*PTR_IN, -R*PTR_OUT, c['pointer'], R*0.11))
    L.append('</svg>')
    return '\n'.join(L)

for name, half, px, R, c in SPECS:
    open('res/%s.svg' % name, 'w').write(build(half, px, R, c))
    print('  %-24s viewBox=%.1f  px=%.3f  R=%.2f  flutes=%d' % (name, 2*half, px, R, FLUTES))
