#!/usr/bin/env python3
"""Data-driven panel pipeline (Plan B).

Reads a module layout JSON (panel_src/layouts/<module>.json) — the single source
of truth — and emits BOTH:
  1. res/panels/<Module>_panel_{dark,light}.svg   (for render + Inkscape review)
     Control wells carry SvgHelper-compatible ids (e.g. id="input_CAUSEWAY_..."),
     so a future runtime live-reload binding is a drop-in.
  2. src/gen/<CppStruct>.gen.hpp                   (constexpr mm coords by enum id)
     The widget includes this and wraps each coord with mm2px() at the call site;
     it keeps ALL its own draw/step/theme/menu logic. Codegen owns ONLY placement.

Screws are NOT emitted here — they are drawn in C++ (ui/RedScrew.hpp), the project
standard. Run from the repo root so res/logo/ paths resolve.

Usage:  python3 panel_src/gen_layout.py panel_src/layouts/causeway.json
        python3 panel_src/gen_layout.py --all
"""
import sys, os, json, glob, re
sys.path.insert(0, os.path.dirname(__file__))
import dotmod_design as D
from dotmod_design import px

LAYOUTS_DIR = "panel_src/layouts"
GEN_DIR     = "src/gen"
PANELS_DIR  = "res/panels"


def _color(palette, name_or_hex):
    """Resolve a palette name to hex; pass through literal #hex."""
    if isinstance(name_or_hex, str) and name_or_hex.startswith("#"):
        return name_or_hex
    return palette.get(name_or_hex, "#888888")


def _well(ctrl, palette):
    """An SvgHelper-named well circle for one control."""
    x, y = px(ctrl["x_mm"]), px(ctrl["y_mm"])
    ring = _color(palette, ctrl.get("ring", "line"))
    fill = _color(palette, "well")
    # radius by kind: params (trims) a touch smaller than jacks
    r = px(3.2) if ctrl.get("kind") == "param" else px(4.4)
    # SvgHelper convention: input_/output_/param_ prefix + id.
    kind = ctrl.get("kind", "input")
    sid = f"{kind}_{ctrl['id']}"
    return (f'<circle id="{sid}" cx="{x:.1f}" cy="{y:.1f}" r="{r:.1f}" '
            f'fill="{fill}" stroke="{ring}" stroke-width="1"/>')


def _section(sec, palette, W_MM):
    if sec.get("kind") == "vline":
        x = px(sec["x_mm"]); y0 = px(sec["y0_mm"]); y1 = px(sec["y1_mm"])
        return (f'<line x1="{x:.1f}" y1="{y0:.1f}" x2="{x:.1f}" y2="{y1:.1f}" '
                f'stroke="{palette.get("line","#2a2f37")}" stroke-width="0.8" stroke-opacity="0.5"/>')
    x, y = px(sec["x_mm"]), px(sec["y_mm"])
    w, h = px(sec["w_mm"]), px(sec["h_mm"])
    tint = _color(palette, sec.get("tint", "line"))
    op = sec.get("opacity", 0.05)
    return (f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" '
            f'rx="{px(2):.1f}" fill="{tint}" fill-opacity="{op}"/>')


def _recess(rc, palette):
    x, y = px(rc["x_mm"]), px(rc["y_mm"])
    w, h = px(rc["w_mm"]), px(rc["h_mm"])
    fill = _color(palette, rc.get("fill", "well"))
    op = rc.get("opacity", 0.5)
    stroke = _color(palette, rc.get("stroke", "line"))
    return (f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" '
            f'rx="{px(2.5):.1f}" fill="{fill}" fill-opacity="{op}" '
            f'stroke="{stroke}" stroke-width="1"/>')


def gen_svg(layout, dark):
    p = layout["panel"]
    W_MM, H_MM = p["width_mm"], p["height_mm"]
    PW, PH = px(W_MM), px(H_MM)
    pal = layout["palette"]
    bg = pal.get("bg", "#070707")
    rail = pal.get("rail", "#111111")
    stripe = pal.get("stripe", "#d4001a")

    o = [D.svg_open(PW, PH)]
    o.append('<g inkscape:label="artwork" inkscape:groupmode="layer">')
    o.append(f'<rect width="{PW}" height="{PH}" fill="{bg}"/>')
    o.append(f'<rect x="0" y="0" width="{PW}" height="14.5" fill="{rail}"/>')
    o.append(f'<rect x="0" y="{PH-14.5:.1f}" width="{PW}" height="14.5" fill="{rail}"/>')
    o.append(f'<rect x="0" y="0" width="{PW}" height="2" fill="{stripe}"/>')
    for sec in layout.get("sections", []):
        o.append(_section(sec, pal, W_MM))
    for rc in layout.get("recesses", []):
        o.append(_recess(rc, pal))
    o.append('</g>')

    # branding
    if "logo" in layout:
        lg = layout["logo"]
        o.append('<g inkscape:label="branding" inkscape:groupmode="layer">')
        o.append(D.logo_embed(dark, lg["x_mm"], lg["y_mm"], lg["width_mm"]))
        o.append('</g>')

    # components layer (SvgHelper-named wells)
    o.append('<g inkscape:label="components" inkscape:groupmode="layer">')
    for ctrl in layout["controls"]:
        o.append(_well(ctrl, pal))
    o.append('</g>')

    o.append('</svg>')
    return "\n".join(o)


def gen_header(layout):
    """Emit constexpr mm coords keyed by enum id."""
    struct = layout["cpp_struct"]
    guard = struct.upper() + "_GEN_HPP"
    lines = [
        "// AUTO-GENERATED by panel_src/gen_layout.py — DO NOT EDIT BY HAND.",
        f"// Source of truth: panel_src/layouts/{layout['module'].lower()}.json",
        f"#ifndef {guard}",
        f"#define {guard}",
        "#include <rack.hpp>",
        "",
        f"// Control positions in MILLIMETRES. Wrap with mm2px() at the call site.",
        f"namespace {struct} {{",
        "    struct P { float x, y; };",
    ]
    for ctrl in layout["controls"]:
        cid = ctrl["id"]
        lines.append(f'    static constexpr P {cid} = {{ {ctrl["x_mm"]:.4f}f, {ctrl["y_mm"]:.4f}f }};')
    # label anchors too (widget draws the text, reads the position here)
    for i, lb in enumerate(layout.get("labels", [])):
        if lb.get("runtime"):
            safe = re.sub(r'[^A-Za-z0-9]', '_', lb["text"]).upper()
            lines.append(f'    static constexpr P LBL_{safe}_{i} = {{ {lb["x_mm"]:.4f}f, {lb["y_mm"]:.4f}f }};')
    lines += ["}", "", f"#endif // {guard}", ""]
    return "\n".join(lines)


def crosscheck(layout):
    """Warn if any control id is missing from the module's enum block in Monsoon.hpp."""
    try:
        hpp = open("src/Monsoon.hpp").read()
    except FileNotFoundError:
        return
    missing = [c["id"] for c in layout["controls"] if c["id"] not in hpp]
    if missing:
        print(f"  [WARN] control ids not found in Monsoon.hpp enums: {missing}")
    else:
        print(f"  [ok] all {len(layout['controls'])} control ids present in enums")


def process(path):
    layout = json.load(open(path))
    mod = layout["module"]
    print(f"== {mod} ==")
    crosscheck(layout)
    for dark in (True, False):
        svg = gen_svg(layout, dark)
        suffix = "dark" if dark else "light"
        out = f"{PANELS_DIR}/{mod}_panel_{suffix}.svg"
        open(out, "w").write(svg)
        print(f"  wrote {out}")
    os.makedirs(GEN_DIR, exist_ok=True)
    hdr = f"{GEN_DIR}/{layout['cpp_struct']}.gen.hpp"
    open(hdr, "w").write(gen_header(layout))
    print(f"  wrote {hdr}")


if __name__ == "__main__":
    args = sys.argv[1:]
    if args == ["--all"]:
        targets = sorted(glob.glob(f"{LAYOUTS_DIR}/*.json"))
    else:
        targets = args or sorted(glob.glob(f"{LAYOUTS_DIR}/*.json"))
    for t in targets:
        process(t)
